version: '3.8'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - /home/msaka/data/wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      network:

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - /home/msaka/data/mariadb_data:/var/lib/mysql
    env_file:
      - ./.env
    networks:
      network:
      
  wordpress:
    container_name: wp-php
    build: ./requirements/wordpress
    volumes:
      - /home/msaka/data/wordpress_data:/var/www/html
    env_file:
      - ./.env
    networks:
      network:

volumes:
  wordpress:
    driver: local
  mariadb_data:
    driver: local

networks:
  network:
    driver: bridge
