FROM debian:buster

RUN apt-get update && \
	apt-get install -y \
	mariadb-server &&\
	apt-get clean &&\
	rm -rf /var/lib/apt/lists/*

RUN mkdir /run/mysqld && \
    chown mysql:mysql /run/mysqld

COPY 50-server.cnf /etc/mysql/mariadb.conf.d/.
COPY tools/init.sql /docker-entrypoint-initdb.d/init.sql



CMD [ "mysqld" ]

