FROM debian:buster

RUN apt-get update && \
	apt-get install -y \
	mariadb-server &&\
	apt-get clean &&\
	rm -rf /var/lib/apt/lists/*

RUN mkdir /run/mysqld && \
    chown mysql:mysql /run/mysqld

COPY 50-server.cnf /etc/mysql/mariadb.conf.d/.

RUN chown -R mysql:mysql /var/lib/mysql
RUN chmod -R 755 /var/lib/mysql

COPY /tools/init.sh /usr/local/bin/init.sh
RUN chmod +x /usr/local/bin/init.sh


CMD ["/usr/local/bin/init.sh"]

