FROM debian:buster

RUN apt-get update && \
    apt-get install -y \
    tar \
    php \
	curl \
    php-fpm \
    php-mysql \
    php-gd \
    php-cli \
    wget && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /var/www/html/wordpress  /run/php

COPY www.conf /etc/php/7.3/fpm/pool.d/.

COPY /tools/wordpress.sh /usr/local/bin/wordpress.sh
RUN chmod +x /usr/local/bin/wordpress.sh

CMD ["/usr/local/bin/wordpress.sh"]